// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retail_Bank_Management.Models;

namespace Retail_Bank_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200726140119_SeedMigration")]
    partial class SeedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Retail_Bank_Management.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SSNID")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 100000000,
                            Address = "S/S MQ 133",
                            Address2 = "Dhori Staff Quarters",
                            Age = (byte)23,
                            City = "Bokaro",
                            Name = "Shashank Sharma",
                            SSNID = 123456789,
                            State = "Jharkhand"
                        },
                        new
                        {
                            CustomerID = 100000001,
                            Address = "MQ 123",
                            Address2 = "Kargali Staff Quarters",
                            Age = (byte)21,
                            City = "Bokaro",
                            Name = "Nikhil Raj",
                            SSNID = 100456789,
                            State = "Jharkhand"
                        },
                        new
                        {
                            CustomerID = 100000002,
                            Address = "S/S SQ 24",
                            Address2 = "Dhori Staff Quarters",
                            Age = (byte)21,
                            City = "Bokaro",
                            Name = "Adarsh Singh",
                            SSNID = 123459789,
                            State = "Jharkhand"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
